package com.example.drainagesystem.entity;

public class Agent {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agent_info.a_id
     *
     * @mbggenerated
     */
    private Integer aId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agent_info.a_company_name
     *
     * @mbggenerated
     */
    private String aCompanyName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agent_info.a_pn
     *
     * @mbggenerated
     */
    private String aPn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agent_info.a_sn
     *
     * @mbggenerated
     */
    private String aSn;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agent_info.a_id
     *
     * @return the value of agent_info.a_id
     *
     * @mbggenerated
     */
    public Integer getaId() {
        return aId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agent_info.a_id
     *
     * @param aId the value for agent_info.a_id
     *
     * @mbggenerated
     */
    public void setaId(Integer aId) {
        this.aId = aId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agent_info.a_company_name
     *
     * @return the value of agent_info.a_company_name
     *
     * @mbggenerated
     */
    public String getaCompanyName() {
        return aCompanyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agent_info.a_company_name
     *
     * @param aCompanyName the value for agent_info.a_company_name
     *
     * @mbggenerated
     */
    public void setaCompanyName(String aCompanyName) {
        this.aCompanyName = aCompanyName == null ? null : aCompanyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agent_info.a_pn
     *
     * @return the value of agent_info.a_pn
     *
     * @mbggenerated
     */
    public String getaPn() {
        return aPn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agent_info.a_pn
     *
     * @param aPn the value for agent_info.a_pn
     *
     * @mbggenerated
     */
    public void setaPn(String aPn) {
        this.aPn = aPn == null ? null : aPn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agent_info.a_sn
     *
     * @return the value of agent_info.a_sn
     *
     * @mbggenerated
     */
    public String getaSn() {
        return aSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agent_info.a_sn
     *
     * @param aSn the value for agent_info.a_sn
     *
     * @mbggenerated
     */
    public void setaSn(String aSn) {
        this.aSn = aSn == null ? null : aSn.trim();
    }
}