package com.example.drainagesystem.entity;

public class Seller {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seller_info.s_id
     *
     * @mbggenerated
     */
    private Integer sId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seller_info.s_company_name
     *
     * @mbggenerated
     */
    private String sCompanyName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seller_info.s_mail_contacts
     *
     * @mbggenerated
     */
    private String sMailContacts;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seller_info.s_mail_contact_number
     *
     * @mbggenerated
     */
    private String sMailContactNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seller_info.s_mailbox_contact
     *
     * @mbggenerated
     */
    private String sMailboxContact;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seller_info.s_service_area
     *
     * @mbggenerated
     */
    private String sServiceArea;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seller_info.s_city
     *
     * @mbggenerated
     */
    private String sCity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seller_info.s_city_level
     *
     * @mbggenerated
     */
    private Integer sCityLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seller_info.s_after_sale_people
     *
     * @mbggenerated
     */
    private String sAfterSalePeople;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seller_info.s_after_sale_mailbox
     *
     * @mbggenerated
     */
    private String sAfterSaleMailbox;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seller_info.s_after_telephone
     *
     * @mbggenerated
     */
    private String sAfterTelephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seller_info.s_remarks
     *
     * @mbggenerated
     */
    private String sRemarks;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seller_info.s_id
     *
     * @return the value of seller_info.s_id
     *
     * @mbggenerated
     */
    public Integer getsId() {
        return sId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seller_info.s_id
     *
     * @param sId the value for seller_info.s_id
     *
     * @mbggenerated
     */
    public void setsId(Integer sId) {
        this.sId = sId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seller_info.s_company_name
     *
     * @return the value of seller_info.s_company_name
     *
     * @mbggenerated
     */
    public String getsCompanyName() {
        return sCompanyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seller_info.s_company_name
     *
     * @param sCompanyName the value for seller_info.s_company_name
     *
     * @mbggenerated
     */
    public void setsCompanyName(String sCompanyName) {
        this.sCompanyName = sCompanyName == null ? null : sCompanyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seller_info.s_mail_contacts
     *
     * @return the value of seller_info.s_mail_contacts
     *
     * @mbggenerated
     */
    public String getsMailContacts() {
        return sMailContacts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seller_info.s_mail_contacts
     *
     * @param sMailContacts the value for seller_info.s_mail_contacts
     *
     * @mbggenerated
     */
    public void setsMailContacts(String sMailContacts) {
        this.sMailContacts = sMailContacts == null ? null : sMailContacts.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seller_info.s_mail_contact_number
     *
     * @return the value of seller_info.s_mail_contact_number
     *
     * @mbggenerated
     */
    public String getsMailContactNumber() {
        return sMailContactNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seller_info.s_mail_contact_number
     *
     * @param sMailContactNumber the value for seller_info.s_mail_contact_number
     *
     * @mbggenerated
     */
    public void setsMailContactNumber(String sMailContactNumber) {
        this.sMailContactNumber = sMailContactNumber == null ? null : sMailContactNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seller_info.s_mailbox_contact
     *
     * @return the value of seller_info.s_mailbox_contact
     *
     * @mbggenerated
     */
    public String getsMailboxContact() {
        return sMailboxContact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seller_info.s_mailbox_contact
     *
     * @param sMailboxContact the value for seller_info.s_mailbox_contact
     *
     * @mbggenerated
     */
    public void setsMailboxContact(String sMailboxContact) {
        this.sMailboxContact = sMailboxContact == null ? null : sMailboxContact.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seller_info.s_service_area
     *
     * @return the value of seller_info.s_service_area
     *
     * @mbggenerated
     */
    public String getsServiceArea() {
        return sServiceArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seller_info.s_service_area
     *
     * @param sServiceArea the value for seller_info.s_service_area
     *
     * @mbggenerated
     */
    public void setsServiceArea(String sServiceArea) {
        this.sServiceArea = sServiceArea == null ? null : sServiceArea.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seller_info.s_city
     *
     * @return the value of seller_info.s_city
     *
     * @mbggenerated
     */
    public String getsCity() {
        return sCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seller_info.s_city
     *
     * @param sCity the value for seller_info.s_city
     *
     * @mbggenerated
     */
    public void setsCity(String sCity) {
        this.sCity = sCity == null ? null : sCity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seller_info.s_city_level
     *
     * @return the value of seller_info.s_city_level
     *
     * @mbggenerated
     */
    public Integer getsCityLevel() {
        return sCityLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seller_info.s_city_level
     *
     * @param sCityLevel the value for seller_info.s_city_level
     *
     * @mbggenerated
     */
    public void setsCityLevel(Integer sCityLevel) {
        this.sCityLevel = sCityLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seller_info.s_after_sale_people
     *
     * @return the value of seller_info.s_after_sale_people
     *
     * @mbggenerated
     */
    public String getsAfterSalePeople() {
        return sAfterSalePeople;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seller_info.s_after_sale_people
     *
     * @param sAfterSalePeople the value for seller_info.s_after_sale_people
     *
     * @mbggenerated
     */
    public void setsAfterSalePeople(String sAfterSalePeople) {
        this.sAfterSalePeople = sAfterSalePeople == null ? null : sAfterSalePeople.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seller_info.s_after_sale_mailbox
     *
     * @return the value of seller_info.s_after_sale_mailbox
     *
     * @mbggenerated
     */
    public String getsAfterSaleMailbox() {
        return sAfterSaleMailbox;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seller_info.s_after_sale_mailbox
     *
     * @param sAfterSaleMailbox the value for seller_info.s_after_sale_mailbox
     *
     * @mbggenerated
     */
    public void setsAfterSaleMailbox(String sAfterSaleMailbox) {
        this.sAfterSaleMailbox = sAfterSaleMailbox == null ? null : sAfterSaleMailbox.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seller_info.s_after_telephone
     *
     * @return the value of seller_info.s_after_telephone
     *
     * @mbggenerated
     */
    public String getsAfterTelephone() {
        return sAfterTelephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seller_info.s_after_telephone
     *
     * @param sAfterTelephone the value for seller_info.s_after_telephone
     *
     * @mbggenerated
     */
    public void setsAfterTelephone(String sAfterTelephone) {
        this.sAfterTelephone = sAfterTelephone == null ? null : sAfterTelephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seller_info.s_remarks
     *
     * @return the value of seller_info.s_remarks
     *
     * @mbggenerated
     */
    public String getsRemarks() {
        return sRemarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seller_info.s_remarks
     *
     * @param sRemarks the value for seller_info.s_remarks
     *
     * @mbggenerated
     */
    public void setsRemarks(String sRemarks) {
        this.sRemarks = sRemarks == null ? null : sRemarks.trim();
    }
}