server:
  port: 9999
  servlet:
    context-path: /drainage-system
spring:
      datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost/drainage_tool
        username: root
        password: password
#      mvc:
#        view:
#          prefix: classpath:/templates/
#          suffix: .html
      resources:
        static-locations: classpath:/resources/,classpath:/templates/,classpath:/static/
mybatis:
  type-aliases-package: com.example.drainagesystem.entity  # 注意：对应实体类的路径
  mapper-locations: classpath:/mapper/**Mapper.xml


