package com.example.drainagesystem.dao;

import com.example.drainagesystem.entity.Agent;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface AgentMapper {

    List<Agent> getSelectAgent(@Param("sn") String sn);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer aId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent_info
     *
     * @mbggenerated
     */
    int insert(Agent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent_info
     *
     * @mbggenerated
     */
    int insertSelective(Agent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent_info
     *
     * @mbggenerated
     */
    //Agent selectByPrimaryKey(Integer aId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Agent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Agent record);
}