package com.example.drainagesystem.dao;

import com.example.drainagesystem.entity.Drainage;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface DrainageMapper {
    List<String> getSelectDrainage(@Param("pn")String pn , @Param("province")String province);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drainage_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer dId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drainage_info
     *
     * @mbggenerated
     */
    int insert(Drainage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drainage_info
     *
     * @mbggenerated
     */
    int insertSelective(Drainage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drainage_info
     *
     * @mbggenerated
     */
    Drainage selectByPrimaryKey(Integer dId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drainage_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Drainage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drainage_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Drainage record);
}